on:
  push:
    branches:    
      - 3.14
      - production
      - development

env:
  REGISTRY_IMAGE: alfredcapital/symmetric-ds

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: write
    defaults:
      run:
        shell: bash

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: depot/setup-action@v1

      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Bake and push symmetric-ds
        uses: depot/build-push-action@v1
        with:
          context: ./symmetric-assemble
          platforms: linux/amd64,linux/arm64
          push: true
          load: true
          pull: true
          tags: ${{ env.REGISTRY_IMAGE }}:latest, ${{ env.REGISTRY_IMAGE }}:${{ github.sha }}
          project: c6f755fnlh